/*
 * GUI.java
 *
 * Created on 17 luglio 2008, 13.51
 */
package GUI.old;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * @author dariospy
 */
public class GUI extends javax.swing.JFrame {

	/*

  INIZIO CODICE SCRITTO A MANO

*/
	private int registerBuffer = 0;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField LV;
	private javax.swing.JTextField PC;
	private javax.swing.JButton Reset;
	private javax.swing.JTextField SP;
	private javax.swing.JButton Start;
	private javax.swing.JButton Step;
	private javax.swing.JButton Stop;
	private javax.swing.JButton setStdinBtn;
	private javax.swing.JTextField TOS;
	private javax.swing.JRadioButton binary;
	private javax.swing.JTextArea contants;
	private javax.swing.JRadioButton hex;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTextArea methods;
	private javax.swing.JTextArea output;
	private javax.swing.JTextArea prgram;
	private javax.swing.JTextField running;
	private javax.swing.JTextArea stdout;
	private javax.swing.JTextArea stdin;
	private Stack stack;
	private javax.swing.JButton translate;

	/**
	 * Creates new form GUI
	 */
	public GUI() {
		initComponents();
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
		setLocation((int) ((dim.getWidth() - this.getWidth()) / 2),
				(int) ((dim.getHeight() - this.getHeight()) / 2));
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jPanel12 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		stdin = new javax.swing.JTextArea();
		setStdinBtn = new javax.swing.JButton();
		stdout = new javax.swing.JTextArea();
		prgram = new javax.swing.JTextArea();
		jPanel6 = new javax.swing.JPanel();
		jPanel11 = new javax.swing.JPanel();
		jPanel13 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		output = new javax.swing.JTextArea();
		jPanel7 = new javax.swing.JPanel();
		translate = new javax.swing.JButton();
		Start = new javax.swing.JButton();
		Reset = new javax.swing.JButton();
		Stop = new javax.swing.JButton();
		Step = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		stack = new Stack();
		jPanel4 = new javax.swing.JPanel();
		jPanel8 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		methods = new javax.swing.JTextArea();
		binary = new javax.swing.JRadioButton();
		hex = new javax.swing.JRadioButton();
		jPanel9 = new javax.swing.JPanel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jScrollPane5 = new javax.swing.JScrollPane();
		contants = new javax.swing.JTextArea();
		jPanel10 = new javax.swing.JPanel();
		running = new javax.swing.JTextField();
		TOS = new javax.swing.JTextField();
		SP = new javax.swing.JTextField();
		LV = new javax.swing.JTextField();
		PC = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("emuIJVM");
		setName("emuIJVM"); // NOI18N
		setResizable(false);

		jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Standard Output"));

		stdout.setBackground(new java.awt.Color(0, 0, 0));
		stdout.setFont(new java.awt.Font("DejaVu Sans", 0, 14));
		stdout.setForeground(new java.awt.Color(255, 255, 255));
		stdout.setTabSize(5);
		stdout.setEditable(false);
		stdout.setToolTipText("Your Program Output");
		stdout.setCaretColor(new java.awt.Color(255, 255, 255));
		jScrollPane5.setViewportView(stdout);

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(
				jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
		);
		jPanel11Layout.setVerticalGroup(
				jPanel11Layout.createParallelGroup(GroupLayout.Alignment.CENTER)
						.addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
		);


		jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Standard Input"));

		stdin.setBackground(new java.awt.Color(0, 0, 0));
		stdin.setFont(new java.awt.Font("DejaVu Sans", 0, 14));
		stdin.setForeground(new java.awt.Color(255, 255, 255));
		stdin.setTabSize(5);
		stdin.setEditable(true);
		stdin.setRows(1);
		stdin.setToolTipText("Your Program Input");
		stdin.setCaretColor(new java.awt.Color(255, 255, 255));

		setStdinBtn.setText("Set");
		setStdinBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout.setHorizontalGroup(
				jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
								.addComponent(stdin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, 400 - 63)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(setStdinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
						));
		jPanel13Layout.setVerticalGroup(
				jPanel13Layout.createParallelGroup(GroupLayout.Alignment.CENTER)
						.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(stdin, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
								.addComponent(setStdinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
						));


		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout.setHorizontalGroup(
				jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
								.addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(0, 0, 0)))
						.addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(0, 0, 0)
		);
		jPanel12Layout.setVerticalGroup(
				jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel12Layout.createSequentialGroup()
								.addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		);

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Assembly IJVM Program"));

		prgram.setBackground(new java.awt.Color(0, 0, 0));
		prgram.setColumns(20);
		prgram.setFont(new java.awt.Font("DejaVu Sans", 0, 14));
		prgram.setForeground(new java.awt.Color(255, 255, 255));
		prgram.setRows(5);
		prgram.setTabSize(5);
		prgram.setToolTipText("Your Program Here");
		prgram.setCaretColor(new java.awt.Color(255, 255, 255));
		jScrollPane1.setViewportView(prgram);
		TextLineNumber lineNumber = new TextLineNumber(prgram);
		prgram.setBorder(BorderFactory.createEmptyBorder(0, 3, 0, 0));
		jScrollPane1.setRowHeaderView(lineNumber);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
		);
		jPanel5Layout.setVerticalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
		);

		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Assembler Output"));

		output.setBackground(new java.awt.Color(0, 0, 0));
		output.setColumns(20);
		output.setEditable(false);
		output.setFont(new java.awt.Font("Monospaced", 0, 10));
		output.setForeground(new java.awt.Color(255, 255, 255));
		output.setRows(5);
		jScrollPane2.setViewportView(output);

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
		);
		jPanel6Layout.setVerticalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
		);

		jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "IJVM Control Panel"));

		translate.setText("Translate & Load");
		translate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		Start.setText("Start");
		Start.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		Reset.setText("Reset");
		Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		Stop.setText("Stop");
		Stop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		Step.setText("Step");
		Step.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addContainerGap(192, Short.MAX_VALUE)
								.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
												.addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Step, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
												.addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap())
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(translate)
								.addContainerGap(230, Short.MAX_VALUE))
		);
		jPanel7Layout.setVerticalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel7Layout.createSequentialGroup()
												.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
												.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Step, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(jPanel7Layout.createSequentialGroup()
												.addGap(21, 21, 21)
												.addComponent(translate)))
								.addContainerGap())
		);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(0, 0, 0))
		);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Stack Evolution"));
		jPanel3.setDoubleBuffered(false);

		stack.setBackground(new java.awt.Color(204, 204, 255));

		javax.swing.GroupLayout stackLayout = new javax.swing.GroupLayout(stack);
		stack.setLayout(stackLayout);
		stackLayout.setHorizontalGroup(
				stackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 284, Short.MAX_VALUE)
		);
		stackLayout.setVerticalGroup(
				stackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 638, Short.MAX_VALUE)
		);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(stack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(stack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);

		jPanel4.setDoubleBuffered(false);

		jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Method Area"));

		methods.setBackground(new java.awt.Color(0, 0, 0));
		methods.setColumns(20);
		methods.setEditable(false);
		methods.setFont(new java.awt.Font("Monospaced", 0, 12));
		methods.setForeground(new java.awt.Color(255, 255, 255));
		methods.setRows(5);
		jScrollPane3.setViewportView(methods);

		binary.setText("Bin");

		hex.setText("Hex");

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(binary)
								.addGap(18, 18, 18)
								.addComponent(hex)
								.addContainerGap(229, Short.MAX_VALUE))
						.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
		);
		jPanel8Layout.setVerticalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(binary)
										.addComponent(hex))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
		);

		jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Constant Pool"));

		contants.setBackground(new java.awt.Color(0, 0, 0));
		contants.setColumns(20);
		contants.setEditable(false);
		contants.setFont(new java.awt.Font("Monospaced", 0, 12));
		contants.setForeground(new java.awt.Color(255, 255, 255));
		contants.setRows(5);
		jScrollPane4.setViewportView(contants);

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
		);
		jPanel9Layout.setVerticalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
		);

		jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mic-1 Status"));

		running.setBackground(new java.awt.Color(255, 255, 255));
		running.setEditable(false);
		running.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		TOS.setBackground(new java.awt.Color(255, 255, 255));
		TOS.setEditable(false);
		TOS.setHorizontalAlignment(javax.swing.JTextField.CENTER);


		SP.setBackground(new java.awt.Color(255, 255, 255));
		SP.setEditable(false);
		SP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		LV.setBackground(new java.awt.Color(255, 255, 255));
		LV.setEditable(false);
		LV.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		PC.setBackground(new java.awt.Color(255, 255, 255));
		PC.setEditable(false);
		PC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jLabel1.setText("Is running");

		jLabel2.setText("TOS");

		jLabel3.setText("SP");

		jLabel4.setText("LV");

		jLabel5.setText("PC");

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout.setHorizontalGroup(
				jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel10Layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel1)
										.addComponent(jLabel2)
										.addComponent(jLabel3)
										.addComponent(jLabel4)
										.addComponent(jLabel5))
								.addGap(18, 18, 18)
								.addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(PC, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(LV, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(SP, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(TOS, javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(running, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(28, Short.MAX_VALUE))
		);
		jPanel10Layout.setVerticalGroup(
				jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(running, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(TOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(LV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel4))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel5))
								.addContainerGap())
		);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGap(0, 0, 0))
		);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)
								.addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0))
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);

		jMenu1.setText("File");

		jMenuItem8.setText("New Program");
		jMenu1.add(jMenuItem8);

		jMenuItem3.setText("Open Program");
		jMenu1.add(jMenuItem3);

		jMenuItem4.setText("Save Program");
		jMenu1.add(jMenuItem4);

		jMenuItem5.setText("Exit");
		jMenu1.add(jMenuItem5);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");

		jMenuItem1.setText("MicroProgram");
		jMenu2.add(jMenuItem1);

		jMenuItem2.setText("Opcode List");
		jMenu2.add(jMenuItem2);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("?");

		jMenuItem6.setText("Help");
		jMenu3.add(jMenuItem6);

		jMenuItem7.setText("About");
		jMenu3.add(jMenuItem7);

		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		);

		pack();
	}

	public void setCompileHandler(ActionListener _toSet) {
		translate.addActionListener(_toSet);
	}

	public void setStartHandler(ActionListener _toSet) {
		Start.addActionListener(_toSet);
	}

	public void setStopHandler(ActionListener _toSet) {
		Stop.addActionListener(_toSet);
	}

	public void setResetHandler(ActionListener _toSet) {
		Reset.addActionListener(_toSet);
	}

	public void setHexBinaryHandler(ActionListener _toSet) {
		hex.addActionListener(_toSet);
		binary.addActionListener(_toSet);
	}

	public void setStepHandler(ActionListener _toSet) {
		Step.addActionListener(_toSet);
	}

	public void setSetStdinBtn(ActionListener _toSet) {
		setStdinBtn.addActionListener(_toSet);
	}

	public void setMenuHandler(ActionListener _toSet) {

		jMenuItem1.addActionListener(_toSet);
		jMenuItem2.addActionListener(_toSet);
		jMenuItem3.addActionListener(_toSet);
		jMenuItem8.addActionListener(_toSet);
		jMenuItem4.addActionListener(_toSet);
		jMenuItem5.addActionListener(_toSet);
		jMenuItem6.addActionListener(_toSet);
		jMenuItem7.addActionListener(_toSet);
	}

	//abilita/disabilita il pulsante start
	public void setStart(boolean toSet) {
		Start.setEnabled(toSet);
	}

	public void setStop(boolean toSet) {
		Stop.setEnabled(toSet);
	}

	public void setReset(boolean toSet) {
		Reset.setEnabled(toSet);
	}

	public void setStep(boolean toSet) {
		Step.setEnabled(toSet);
	}

	public void setTranslate(boolean toSet) {
		translate.setEnabled(toSet);
	}

	public void setProgram(String toSet) {
		prgram.setText(toSet);
	}

	public void setStdout(String toSet) {
		stdout.setText(toSet);
	}

	public void setStdin(String toSet) {
		stdin.setText(toSet);
	}

	public void appendStdout(String toSet) {
		stdout.append(toSet);
	}

	public void setOutput(String toOut) {
		output.setText(toOut);
	}

	public void setHex(boolean toSet) {
		hex.setSelected(toSet);
	}

	public void setBinary(boolean toSet) {
		binary.setSelected(toSet);
	}

	public String getProgramString() {
		return prgram.getText();
	}

	public String getStdoutString() {
		return stdout.getText();
	}

	public String getStdinString() {
		return stdin.getText();
	}

	public void setMethodArea(String toSet) {
		methods.setText(toSet);
	}

	public void setConstantPool(String toSet) {
		contants.setText(toSet);
	}

	public void setSP(int toSet) {
		SP.setText((new Integer(toSet)).toString());
	}

	public void setLV(int toSet) {
		LV.setText((new Integer(toSet)).toString());
	}

	public void setPC(int toSet) {
		PC.setText((new Integer(toSet)).toString());
	}

	public void setRunning(boolean toSet) {
		running.setText(toSet ? "true" : "false");
	}

	public void setTOS(int toSet) {
		TOS.setText((new Integer(toSet)).toString());
	}

	public void printRegisters(int _numRegistri) {
		registerBuffer = registerBuffer + _numRegistri;
		if (_numRegistri > 0)
			for (int i = 0; i < _numRegistri; i++)
				stack.insertRegister();

	}

	public void deleteRegisters(int _numRegistri) {
		registerBuffer = registerBuffer - _numRegistri;
		for (int i = 0; i < _numRegistri; i++)
			stack.deleteRegister();
	}

	public void stackError() {
		stack.error();
		stack.repaint();
	}

	public void setStackValues(int[] toSet) {
		stack.setStackValues(toSet);
	}

	public void refreshStack() {
		stack.repaint();
	}
	// End of variables declaration//GEN-END:variables

}
