/*
 * OpcodeView.java
 *
 * Created on 21 luglio 2008, 18.58
 */

package GUI.Dialogs;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;

import Assembler.Parametro;

/**
 * @author dariospy
 */
public class OpcodeView extends javax.swing.JDialog
{

    /**
     * Creates new form OpcodeView
     */
    public OpcodeView(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) ((dim.getWidth() - this.getWidth()) / 2),
                (int) ((dim.getHeight() - this.getHeight()) / 2));
        isLarge.addActionListener(new largeHandler());
        param.addListSelectionListener(new listHandler());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        name = new javax.swing.JTextField();
        value1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        param = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        nuovo = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        isLarge = new javax.swing.JCheckBox();
        value2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opcode editor");
        setResizable(false);

        name.setColumns(10);
        jScrollPane1.setViewportView(param);
        jLabel1.setText("Name");
        jLabel2.setText("Value 1");
        jLabel3.setText("Parameters");
        edit.setText("Edit");
        edit.setEnabled(false);
        save.setText("Save & Close");
        nuovo.setText("New");
        delete.setText("Delete");
        delete.setEnabled(false);
        isLarge.setText("Large");
        value2.setText("");
        jLabel4.setText("Value 2");
        //param.setFont(new java.awt.Font("Monospaced", 0, 14));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel1))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                                                        .addComponent(value1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                                                        .addComponent(isLarge, javax.swing.GroupLayout.Alignment.LEADING)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(21, 21, 21)
                                                                                .addComponent(jLabel4))
                                                                        .addComponent(jLabel3))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(value2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(delete)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(edit)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(nuovo))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addComponent(save)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(value1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isLarge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(value2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(delete)
                                                        .addComponent(edit)
                                                        .addComponent(nuovo)))
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(save)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /*
      INIZIO CODICE SCRITTO A MANO
    */
    public void setHandler(ActionListener handler)
    {
        edit.addActionListener(handler);
        delete.addActionListener(handler);
        nuovo.addActionListener(handler);
        save.addActionListener(handler);
    }

    public void setList(Parametro[] toSet)
    {
        param.setListData(toSet);
        delete.setEnabled(false);
        edit.setEnabled(false);
    }

    public void setLarge(boolean isLargeB)
    {
        isLarge.setSelected(isLargeB);
        value2.setEnabled(isLargeB);
    }

    public String getName()
    {
        return name.getText();
    }

    public String getValue1()
    {
        return value1.getText();
    }

    public String getValue2()
    {
        return value2.getText();
    }

    public void setName(String toSet)
    {
        name.setText(toSet);
    }

    public void setValue1(String toSet)
    {
        value1.setText(toSet);
    }

    public void setValue2(String toSet)
    {
        value2.setText(toSet);
    }


    public boolean isLarge()
    {
        return isLarge.isSelected();
    }

    //restituisce l'indice selezionato nella lista
    public int getSelectedIndex()
    {
        return param.getSelectedIndex();
    }


    private class largeHandler implements ActionListener
    {
        public void actionPerformed(ActionEvent event)
        {
            value2.setEnabled(isLarge.isSelected());
        }
    }

    private class listHandler implements ListSelectionListener
    {
        public void valueChanged(ListSelectionEvent event)
        {
            edit.setEnabled(true);
            delete.setEnabled(true);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JCheckBox isLarge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton nuovo;
    private javax.swing.JList param;
    private javax.swing.JButton save;
    private javax.swing.JTextField value1;
    private javax.swing.JTextField value2;
    // End of variables declaration

}
