/*
 * Parameter.java
 *
 * Created on 21 luglio 2008, 19.06
 */

package GUI.Dialogs;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;

/**
 * @author dariospy
 */
public class Parameter extends javax.swing.JDialog
{

    /**
     * Creates new form Parameter
     */
    public Parameter(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) ((dim.getWidth() - this.getWidth()) / 2),
                (int) ((dim.getHeight() - this.getHeight()) / 2));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        radioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        variable = new javax.swing.JRadioButton();
        label = new javax.swing.JRadioButton();
        direct = new javax.swing.JRadioButton();
        constant = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        bytes = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        setTitle("Parameter editor");
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Type"));

        radioGroup.add(variable);
        variable.setText("Variable");

        radioGroup.add(label);
        label.setText("Label");

        radioGroup.add(direct);
        direct.setText("Direct");

        radioGroup.add(constant);
        constant.setText("Constant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(direct)
                                .addGap(18, 18, 18)
                                .addComponent(constant)
                                .addGap(18, 18, 18)
                                .addComponent(variable)
                                .addGap(18, 18, 18)
                                .addComponent(label)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(direct)
                                .addComponent(constant)
                                .addComponent(variable)
                                .addComponent(label))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bytes (MAX 4)"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bytes, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bytes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ok.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(155, Short.MAX_VALUE)
                                .addComponent(ok)
                                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ok)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
      INIZIO CODICE SCRITTO A MANO
    */
    public void setHandler(ActionListener toSet)
    {
        ok.addActionListener(toSet);
    }

    public int getSelected()
    {
        if (direct.isSelected())
            return 0;
        if (constant.isSelected())
            return 1;
        if (variable.isSelected())
            return 2;
        if (label.isSelected())
            return 3;
        return -1;
    }

    public void select(String toSelect)
    {
        if (toSelect.equals("Constant"))
            constant.setSelected(true);
        else if (toSelect.equals("Direct"))
            direct.setSelected(true);
        else if (toSelect.equals("Variable"))
            variable.setSelected(true);
        else if (toSelect.equals("Label"))
            label.setSelected(true);
    }

    public void setBytes(String toSet)
    {
        bytes.setText(toSet);
    }

    public String getBytes()
    {
        return bytes.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bytes;
    private javax.swing.JRadioButton constant;
    private javax.swing.JRadioButton direct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton label;
    private javax.swing.JButton ok;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton variable;
    // End of variables declaration//GEN-END:variables

}
